# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0004_post_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='site',
        ),
    ]
