# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0010_auto_20170722_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
