# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0011_auto_20170722_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blogengine.Tag'),
        ),
    ]
